# -*- coding: utf-8 -*-
"""IBM_DataScience.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DKN3hEdSKrNlr31dmV3NLpPumITJt5EQ

# **Exercise 2**
# **Data Science Project**

# **Exercise** 3
# **Introduction**
In this notebook, we will explore various data science concepts, including programming languages, libraries, tools, and mathematical operations. The exercises will help solidify knowledge in core aspects of data science.

# **Exercise 4**
# **Data Science Languages**
Some popular programming languages used in data science are:

Python
R
SQL
Julia
Java
Scala

# **Exercise 5**
# **Data Science Libraries**
Commonly used libraries in data science include:

Pandas
NumPy
Matplotlib
Scikit-learn
TensorFlow
Keras

# **Exercise 6**
# **Data Science Tools**
**Tool**--------------------**Description**


---





Jupyter Notebooks----------	Interactive notebooks for coding

RStudio--------------------	IDE for R

Apache Spark---------------	Distributed computing framework

TensorFlow----------------	Deep learning framework

Tableau--------------------	Data visualization tool

# **Exercise 7**
# **Arithmetic Expression Examples**
Below are examples of arithmetic expressions, which include addition and multiplication of numbers.

# Exercise **8**
"""

# Multiplying and adding numbers
result = (5 * 3) + 10
print(result)

"""# Exercise **9**"""

# Convert minutes to hours
minutes = 150
hours = minutes / 60
print(hours)

"""# **Exercise 10**
# **Objectives**
Learn about different data science languages
Explore common data science libraries and tools
Practice arithmetic operations
Convert time units using Python

# **Exercise 11**
**Author**
# **Vinay Dodla**
"""